- name: Loop Demo - Remove Built-in Packages
  hosts: web
  become: yes
  tasks:
    - name: Remove builtin packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'mysql', state: 'absent' }
        - { name: 'httpd', state: 'absent' }
        - { name: 'nginx', state: 'absent' }