- name: Print personal information
  hosts: web
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Print personal information
      ansible.builtin.debug:
        msg: "Hi hello am {{Name}}, amd my native is {{From}}"