- name: Print personal information
  hosts: web
  become: yes
  vars_files:
  - vars.yaml

 tasks:
    - name: Print personal information
      ansible.builtin.debug:
        msg: "hi hello{{Name}}, anm my namtive is {{From}}"