- name: Variable from prompt
  hosts: web
  become: yes
  vars_prompt:
    - name: chethan
      prompt: Please enter username
      private: false
    - name: c1234
      prompt: Please enter password
      private: true

  tasks:
    - name: Print user name and password
      ansible.builtin.debug:
        msg: "Hi hello, I am {{ chethan }}, and my password is  {{ 1234 }}"