- name: Create a file
  hosts: all
  become: yes

  tasks:
    - name: Create a directory
      file:
         name: test-dir
         path: /root/test-dir
         state: directory
         mode: '0777'

    - name: Create file
      file:
      path: /root/testfile1
      state: touch          