- name: Create User if Not Exists
  hosts: web
  vars_files:
    - secrets.yml
  tasks:
    - name: Check if User Exists
      ansible.builtin.command: id chethan
      register: USER
      ignore_errors: true
    - name: print user information
      ansible.builtin.debug:
        msg: "user info: {{ USER }}"

    - name: Create User
      ansible.builtin.user:
        name: chethan
        state: present
      when: USER.rc != 0