- name: check the status ngnix in multiple server
  become: yes
  hosts: all
  tasks:
    - name: check status of nginx
      ansible.builtin.shell: systemctl status nginx
      register: nginx_status_service
      ignore_errors: true
       
    - name: print nginx status
      ansible.builtin.debug:
       msg: "nginx status: {{ nginx_status_service  }}"
      when: nginx_status.service.stdout! ="active"
    
