# health_check.yml
- name: Check the status of my_critical_service
  hosts: all_servers  # Or specify a specific group of servers
  tasks:
    - name: Check service status
      ansible.builtin.shell: "systemctl is-active my_critical_service"
      register: service_status
      ignore_errors: true
    - name: Report servers with service down
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} - Service is down"
      when: service_status.stdout != "active"
    - name: Check recent logs
      ansible.builtin.shell: "journalctl -u my_critical_service --since '10 minutes ago'"
      register: service_logs
      when: service_status.stdout != "active"
    - name: Print service logs for debugging
      ansible.builtin.debug:
       var: service_logs.stdout_lines
      when: service_status.stdout != "active"

    - name: Restart the service if it is down
      ansible.builtin.systemd:
       name: my_critical_service
      state: restarted
      when: service_status.stdout != "active"

    - name: Confirm service is active
      ansible.builtin.shell: "systemctl is-active my_critical_service"
      register: final_status
    - name: Report any servers where the service is still down
      ansible.builtin.debug:
      msg: "{{ inventory_hostname }} - Service failed to start"
      when: final_status.stdout != "active" 