- name: Check the service status of my critical server
  become: yes
  hosts: all:web
  tasks:
    - name: Check the status of mu all servers
      ansible.builtin.shell: "systemctl is-active my-critical_service"
      register: service_status
      ignore_errors: true
    - name: Report the server with the service down
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}-Service is down"
      when: service_status.stdout != "active"