- name: install packages in loop
  hosts: web
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - mysql
        - httpd
        - nginx
        - postfix  
