- name: create ec2 and Route53
  hosts: local
  become: yes

  vars:
  subnet_id: "subnet-0339e283bff834529"
  sg_id: "sg-0e5538fb0cc47b2e5"
  ami_id: "ami-09c813fb71547fc4f"
  instances:
     - frontend:
     - apiserver:
     - backendserver:
     zone: cheswini.shop
  tasks:
  - name: install boto3 and boot core
    ansible.builtin.pip:
      name:
        - boto3
        - botocore
        executable: pip3.9
