- name: Create EC2 and Route 53 records
  hosts: localhost
  connection: localhost
  vars_files:
    - ec2_vars.yaml
  tasks:
     - name: create ec2_instances
       amazon.aws.ec2_instance:
         name: "{{ item }}"
         vpc_subnet_id: "{{ subnet_id }}"
         instance_type: t2.micro
         security_group: "{{ sg_id }}"
         image_id: "{{ ami_id }}"
       loop: "{{ instances }}"
       register: ec2_instances

     - name: print the output
       ansible.builtin.debug:
         msg: "{{ ec2_instances }}"

     - name: create route53 records
       ansible.builtin.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item}}.{{ zone }}"
        type: A
        ttl: 1
        wait: true
        overwrite:
       loop: "{{ ec2_intances.results }}"
         
         


     

     
         