- name: configure mysql server
  hosts: database
  become: yes
  tasks:
     - name: install mysql-server
       ansible.built.package:
         name: mysql-server
         state: present
           
  