- name: install mysql server
  hosts: my-sql
  become: yes
  tasks:
     - name: install mysql-server
       ansible.builtin.package:
         name: mysql-server
         state: 
     - name: start mysql-server
       ansible.builtin.service:
         name: mysqld
         state: started    

  