#playbook to check wheather enterted  nuber is lesser than ten and greater or equal to ten
- name: Check Number is Less Than or Equal to Ten
  hosts: web
  become: true
  vars_prompt:
    - name: number
      prompt: Enter the number
  tasks:
    - name: Print the numbers less than or equal to 10
      ansible.builtin.debug:
        msg: "Given number {{ number }}, is less than or equal to 10"
      when: number <= 10