- name: Create User
  hosts: web
  become: yes
  tasks:
    - name: Check if user exists
      ansible.builtin.command: id chethan
      register: user_check
      ignore_errors: yes

    - name: Create user if not exists
      ansible.builtin.command: useradd chethan
      when: user_check.rc != 0