- name: create user
  hosts: web
  become: yes
  tasks:
    - name: check the user exist or not
      ansible.builtin.command: id chethan
      register: USER
      ignore_errors: true

    - name: print user information
      ansible.builtin.debug:
        msg: "user information is {{USER}}"    