- name: Install Nginx on RedHat Systems
  hosts: web
  become: yes
  connection: local
  tasks:
    - name: Check OS Family
      ansible.builtin.debug:
        msg: "Operating System Family: {{ ansible_facts }}"

    - name: Install Nginx on RedHat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat" 


      #install the nginx in the server if operating suystem of the server is Redhat