- name: Install nginx if operating system is redhat
  hosts: web
  become: yes
  connection: local
  tasks:
    - name: print the stats
      ansible.builtin.debug:
        msg: "{{ansible_facts}}"
    - name: install nginx if os is redhat
      ansible.builtin.dnf:
      name: nginx
      state: present
      when: ansible_os_family =="Redhat"