- name: Course information
  hosts: web
  vars:
     Course: devops with mirco degree
     Trainer: sumeeth
     tools:
        ci: jenkins
        cm: ansible
        cloud: aws
     topics:
     - linux
     - shellscript
     - terraform
     - AWS
     - k8

  tasks:
   - name: print course information
     ansible.builtin.debug:
       msg: "hi am learning course {{Course}}, with the trainer {{Trainer}}, covered by topics: {{topics}}, and tools:{{tools}}"     