- name: demo for filter to manipulate data 
  hosts: web
  become: yes
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: hello am learning devops from {{institute | default ('microdegree')}}

    - name: Print message if age is yes
      vars_prompt:
      - name: age
        prompt: Are you more than eighteen years old? (yes/no)
        ansible.builtin.debug:
          msg: "You are over 18."
        when: age | lower == "yes"    
 
     