- name: demo for filter to manipulate data 
  hosts: web
  become: yes
  tasks:
    - name: print the default variable
      ansible.builtin.debug:
        msg: hello am learning devops from {{institute | default ('microdegree')}}

    - name: Convert greeting to uppercase
      vars:
        greeting: "hello bengaluru"
      ansible.builtin.debug:
        msg: "{{ greeting | upper }}"