- name: Create a file
  hosts: all
  become: yes

  tasks:
    - name: Create a directory
      file:
        path: /root/test-dir
        state: directory
        mode: '0755'  # Owner: read, write, execute; Group: read, execute; Others: read, execute

    - name: Create a file
      file:
        path: /root/testfile1
        state: touch
        mode: '0644'  # Owner: read, write; Group, Others: read-only